export const RegexPatterns = {
  unit: /unit\s*=\s*(?:")?(\w+)(?:")?(?:\/(\d+(?:\.\d+)?))?/,
  data: /data\(([^)]+)\)/,
  relation: /\.relation\(\s*(?=.*?\s*spatial\s*=\s*(?:")?(?<spatial>[^"]*?)(?:")?,?)\s*(?=.*?\s*value\s*=\s*(?:")?(?<value>[^"]*?)(?:")?,?)\s*(?=.*?\s*type\s*=\s*(?:")?(?<type>[^"]*?)(?:")?,?)[^)]*\)/,
  buffer: /^buffer\((\d+)\)$/,
  zoom: /zoom\((\d+)\)/,
  method: /method\s*=\s*(?:")?([a-zA-Z]\w*)(?:")?(?:\(\s*(\d+)\s*,\s*(\d+)\s*\))?/,
  // shape: /shape\s*=\s*(?:")?(\w+)(?:")?/,
  // radius: /radius\s*=\s*(\d+)/,
  // blur: /blur\s*=\s*(\d+)/,
  // colorScheme: /colorScheme\s*=\s*(?:")?([a-zA-Z_]+)(?:")?/,
  // valueField: /valueField\s*=\s*(?:")?([a-zA-Z_]+)(?:")?/,
  // fillColor: /color\((?:")?([^"]+)(?:")?\)/,
  // strokeColor: /stroke\(color\s*=\s*(?:")?([^"]+)(?:")?\)/,
  // strokeWidth: /width\s*=\s*(\d+)/,
  // fillOpacity: /(?:[^stroke]\s*)opacity\s*=\s*(\d*\.?\d+)/,
  // strokeOpacity: /stroke\(.*opacity\s*=\s*(\d*\.?\d+)/,
  // domain: /domain\(\[([^\]]+)\]\)/,
  // range: /range\(\[([^\]]+)\]\)/,
  lineColor: /color\s*=\s*(?:")?([^",\)\s]+)(?:")?/,
  lineType: /type\s*=\s*(?:")?(\w+)(?:")?\(([^)]+)\)/,
  lineStrokeWidth: /width\s*=\s*(?:")?([^",\)\s]+)(?:")?/,
  lineHeight: /height\s*=\s*(?:")?([^",\)\s]+)(?:")?/,
  lineOpacity: /opacity\s*=\s*(?:")?([^",\)\s]+)(?:")?/,
  map: /\.map\(([^)]+)\)/,
  // mapBackground: /background\s*=\s*(?:")?([^",]+)(?:")?/,
  // mapStreetName: /street_name\s*=\s*(?:")?([^",]+)(?:")?/,
  mapStreetColor: /street_color\s*=\s*(?:")?([^",]+)(?:")?/,
  mapStreetWidth: /street_width\s*=\s*(\d+(?:\.\d+)?)/,
  // pointX: /x\s*=\s*(?:")?([^"]+)(?:")?/,
  // pointY: /y\s*=\s*(?:")?([^"]+)(?:")?/,
  // pointColor: /color\s*=\s*(?:")?([^"]+)(?:")?/,
  chart: /\.chart\(([\s\S]*?)\)/,
  orientation: /\.orientation\(\s*(?:")?([^",\)\s]+)(?:")?\s*\)/,
  alignment: /\.alignment\(\s*(?:")?([^",\)\s]+)(?:")?\s*\)/,
  // query: /\.query\(([^)]+)\)/,
  // queryRoadDirection: /road direction\s*=\s*(?:")?([^",]+)(?:")?/,
  address: /address\s*=\s*(?:")?([^"]+)(?:")?/,
  radius: /radius\s*=\s*(\d+(?:\.\d+)?)\s*(?:")?([a-zA-Z]+)(?:")?/
};